### PR TITLE
feat: [io] implement sync function for io

### PR DESCRIPTION
**Pull request by misonlan**
implement dfile, dfileinfo, dfileoperator, denumerator, dfilemonitor sync function

Log: implement function

Task: https://pms.uniontech.com/task-view-213913.html

### CODE REVIEW

**Review by Groveer — COMMENTED** [review]
Derror 的用法还是setter和getter 真正调用接口时，用户并没有办法知道何时发生错误  没办法使用DExpected吗？

**Comment by Groveer** [comment]
+1

**Review by xzl01 — COMMENTED** [review]
+1

**Review by dandan-y — COMMENTED** [review]
+1

**Review by toberyan — APPROVED** [review]
+1

**Pull request merged**
